data_path: 'data/input.txt'
epochs: 10000
lr: 4e-4

pre_show_chunk: False
batch_size: 10
set_seed: False
seed: 1377

number_of_head: 8
number_of_layers: 18
head_size: 64
number_of_embedded: 384
chunk_size: 128